### ISSUE TITLE
Exception from Spectre on CLI setup exit

### ISSUE THREAD

**Issue by jas88** [SMI/SmiServices#1402]
System.InvalidOperationException: Could not find color or style ''.
   at Spectre.Console.StyleParser.Parse(String text) in /_/src/Spectre.Console/StyleParser.cs:line 17
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 22
   at Spectre.Console.Markup..ctor(String text, Style style) in /_/src/Spectre.Console/Widgets/Markup.cs:line 43
   at Spectre.Console.TableExtensions.<>c.<AddRow>b__6_0(String column) in /_/src/Spectre.Console/Extensions/TableExtensions.cs:line 160
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Spectre.Console.TableExtensions.AddRow(Table table, String[] columns) in /_/src/Spectre.Console/Extensions/TableExtensions.cs:line 160
   at Setup.Program.AddResult(Table table, CheckEventArgs result, String taskName) in /home/runner/work/SmiServices/SmiServices/src/applications/Setup/Program.cs:line 117
   at Setup.Program.RunUnattended(SetupOptions o) in /home/runner/work/SmiServices/SmiServices/src/applications/Setup/Program.cs:line 89
   at Setup.Program.<>c__DisplayClass1_0.<Main>b__0(SetupOptions o) in /home/runner/work/SmiServices/SmiServices/src/applications/Setup/Program.cs:line 42
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Setup.Program.Main(IEnumerable`1 args) in /home/runner/work/SmiServices/SmiServices/src/applications/Setup/Program.cs:line 33
   at Applications.SmiRunner.Program.<>c__DisplayClass2_0.<Main>b__0(Object service) in /home/runner/work/SmiServices/SmiServices/src/applications/Applications.SmiRunner/Program.cs:line 59
   at Smi.Common.Options.SmiCliInit.<>c__DisplayClass9_0.<ParseServiceVerbAndRun>b__0(Object parsed) in /home/runner/work/SmiServices/SmiServices/src/common/Smi.Common/Options/SmiCliInit.cs:line 114
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at Smi.Common.Options.SmiCliInit.ParseServiceVerbAndRun(IEnumerable`1 args, Type[] targetVerbTypes, Func`2 onParse) in /home/runner/work/SmiServices/SmiServices/src/common/Smi.Common/Options/SmiCliInit.cs:line 108
   at Applications.SmiRunner.Program.Main(String[] args) in /home/runner/work/SmiServices/SmiServices/src/applications/Applications.SmiRunner/Program.cs:line 46

Error (exit code 1): Could not find color or style ''.
[

**Comment by rkm** [comment]
Can we reproduce this still? Let's close this issue if not
