### ISSUE TITLE
Unable to load shared library `Magick.Native-Q16-x64.dll`

### ISSUE THREAD

**Issue by rkm** [SMI/SmiServices#1538]
```console
2023-04-24 15:11:43.2926|FATAL|IsIdentifiableHost|ProcessMessageImpl threw unhandled exception|System.ApplicationException: Could not run Tesseract on '<redacted>'
 ---> System.TypeInitializationException: The type initializer for 'NativeMagickSettings' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'Magick.Native-Q16-x64.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libMagick.Native-Q16-x64.dll: cannot 
open shared object file: No such file or directory
   at ImageMagick.Environment.NativeMethods.X64.Environment_Initialize()
   at ImageMagick.Environment.NativeEnvironment.Initialize() in /_/src/Magick.NET/Native/Helpers/Environment.cs:line 65
   at ImageMagick.Environment.Initialize() in /_/src/Magick.NET/Helpers/Environment.cs:line 21
   at ImageMagick.MagickSettings.NativeMagickSettings..cctor() in /_/src/Magick.NET/Native/Settings/MagickSettings.cs:line 321
   --- End of inner exception stack trace ---
   at ImageMagick.MagickSettings.NativeMagickSettings..ctor() in /_/src/Magick.NET/Native/Settings/MagickSettings.cs:line 343
   at ImageMagick.MagickSettings..ctor() in /_/src/Magick.NET/Settings/MagickSettings.cs:line 33
   at ImageMagick.MagickImage..ctor() in /_/src/Magick.NET/MagickImage.cs:line 41
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomPixelData(IFileInfo fi, DicomFile dicomFile, DicomDataset ds)
   --- End of inner exception stack trace ---
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomPixelData(IFileInfo fi, DicomFile dicomFile, DicomDataset ds)
   at IsIdentifiable.Runners.DicomFileRunner.ValidateDicomFile(IFileInfo fi)
   at Microservices.IsIdentifiable.Service.TesseractStanfordDicomFileClassifier.Classify(IFileInfo dcm) in /home/runner/work/SmiServices/SmiServices/src/microservices/Microservices.IsIdentifiable/Service/TesseractStanfordDicomFileClassifier.cs:line 38
   at Microservices.IsIdentifiable.Service.IsIdentifiableQueueConsumer.ProcessMessageImpl(IMessageHeader header, ExtractedFileStatusMessage statusMessage, UInt64 tag) in /home/runner/work/SmiServices/SmiServices/src/microservices/Microservices.IsIdentifi
able/Service/IsIdentifiableQueueConsumer.cs:line 61
   at Smi.Common.Messaging.Consumer`1.ProcessMessage(BasicDeliverEventArgs deliverArgs) in /home/runner/work/SmiServices/SmiServices/src/common/Smi.Common/Messaging/Consumer.cs:line 115|
```

Libs in previous two releases:
```console
$ file SmiServices-v5.1.3/Magick.Native-Q16-x64.dll.so 
SmiServices-v5.1.3/Magick.Native-Q16-x64.dll.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=9629c7060c06c2158b55bd46e030506e0f3bd46c, not stripped

$ ldd SmiServices-v5.1.3/Magick.Native-Q16-x64.dll.so 
linux-vdso.so.1 =>  (0x00007ffecfff2000)
libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f4ef0e81000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4ef0c65000)
libm.so.6 => /lib64/libm.so.6 (0x00007f4ef0963000)
libc.so.6 => /lib64/libc.so.6 (0x00007f4ef0595000)
/lib64/ld-linux-x86-64.so.2 (0x00007f4ef36d1000)

$ file SmiServices-v5.3.0/Magick.Native-Q16-x64.dll.so 
SmiServices-v5.3.0/Magick.Native-Q16-x64.dll.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=72186bc89b7d4cac41f1b9a89d0762aa5550a0bd, not stripped

$ ldd SmiServices-v5.3.0/Magick.Native-Q16-x64.dll.so 
SmiServices-v5.3.0/Magick.Native-Q16-x64.dll.so: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by SmiServices-v5.3.0/Magick.Native-Q16-x64.dll.so)
SmiServices-v5.3.0/Magick.Native-Q16-x64.dll.so: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by SmiServices-v5.3.0/Magick.Native-Q16-x64.dll.so)
SmiServices-v5.3.0/Magick.Native-Q16-x64.dll.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by SmiServices-v5.3.0/Magick.Native-Q16-x64.dll.so)
linux-vdso.so.1 =>  (0x00007ffc8c52e000)
libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fc27d245000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc27d029000)
libm.so.6 => /lib64/libm.so.6 (0x00007fc27cd27000)
libc.so.6 => /lib64/libc.so.6 (0x00007fc27c959000)
/lib64/ld-linux-x86-64.so.2 (0x00007fc27fd5f000)
````

**Comment by rkm** [comment]
Should be fixed in the latest Magick.NET releases as per https://github.com/dlemstra/Magick.NET/issues/1278
